import { datoGraphql } from "@/graphql/graphql-lib"; // See https://gql-tada.0no.co/ for docs on how this works

// See https://gql-tada.0no.co/ for docs on how this works
// gql.tada is an OPTIONAL system that gives you better TypeScript for your GraphQL queries, based on introspections and autogenerated types.
// If you don't care about TypeScript for your queries, you can also just use a plaintext query and fetch() it directly
// But the developer experience of having typed queries & responses is pretty neat, IMHO, so it's worth your time to set it up

export const TableFragment = datoGraphql(
  //language=gql
  `
        fragment TableFragment on TableBlockRecord @_unmask {
            __typename
            id
            table
            caption
        }`,
);

export const ButtonFragment = datoGraphql(
  //language=gql
  `fragment ButtonFragment on ButtonRecord @_unmask {
        __typename
        id
        label
        primary
        url
    }
    `,
);

export const MediaFragment = datoGraphql(
  //language=gql
  `fragment MediaFragment on ImageBlockRecord @_unmask {
        __typename
        id
        image {
            id
            title
            thumbhash
            tags
            smartTags
            md5
            mimeType
            alt
            author
            basename
            blurUpThumb
            blurhash
            copyright
            exifInfo
            customData
            format
            height
            width
            responsiveImage {
                src
                srcSet
                sizes
                base64
                bgColor
                aspectRatio
                height
                width
            }
            video {
                thumbnailUrl
                thumbhash
                streamingUrl
                title
                width
                height
                blurUpThumb
                blurhash
                alt
            }
        }
    }
    `,
);

export const ArticleQuery = datoGraphql(
  //language=gql
  `
        query ArticleQuery($slug: String!) {
            article(filter: {slug: {eq: $slug}}) {
                id
                title
                slug
                content {
                    value
                    blocks {
                        ...TableFragment
                        ...ButtonFragment
                        ...MediaFragment
                    }
                    links {
                        ... on FaqModelRecord {
                            __typename
                            id
                            faq {
                                __typename
                                id
                                question
                                answer {
                                    value
                                    blocks {
                                        ...TableFragment
                                        ... on NewsletterSubscriptionRecord {
                                            __typename
                                            id
                                        }
                                        ... on CtaButtonWithImageRecord {
                                            __typename
                                            id
                                        }
                                    }
                                }
                            }
                        }

                        ... on ArticleRecord {
                            __typename
                            id
                            slug
                            title
                        }
                    }
                }
            }
        }`,
  [TableFragment, ButtonFragment, MediaFragment],
);

export const AllArticlesQuery = datoGraphql(
  //language=graphql
  `
        query MyQuery {
            allArticles(first: "500") {
                slug
                id
                title
            }
        }`,
);
